[#ftl]
[#-- @implicitly included --]
[#-- @ftlvariable name="posts" type="" --]
[#-- @ftlvariable name="users" type="ru.itmo.web.lesson4.model.User[]" --]
[#-- @ftlvariable name="user" type="ru.itmo.web.lesson4.model.User" --]
